### ISSUE TITLE
crayons.ColoredString can't be converted into string in specific cases

### ISSUE THREAD

**Issue by gjeusel** [maarten-dp/flask-restless-client#32] opened 2020-08-20 16:02 UTC
Wtf of a bug !! Only happening when in multiproc - multithread of dramatiq.
Managed to reproduce in docker only.

Traceback:
```sh
dramatiq-worker_1     |   File "/usr/local/lib/python3.6/site-packages/restless_client/client.py", line 219, in __init__
dramatiq-worker_1     |     self.initialize()
dramatiq-worker_1     |   File "/usr/local/lib/python3.6/site-packages/restless_client/client.py", line 226, in initialize
dramatiq-worker_1     |     check_server_compatibility(meta.get('server_version'))
dramatiq-worker_1     |   File "/usr/local/lib/python3.6/site-packages/restless_client/utils.py", line 153, in check_server_compatibility
dramatiq-worker_1     |     warnings.warn(str(crayons.yellow(message.format(*params))))
dramatiq-worker_1     | TypeError: __str__ returned non-string (type function)
```

See [similar issue](https://github.com/SergeyPirogov/webdriver_manager/issues/60)

**Comment by maarten-dp** [comment] 2020-08-21 09:55
> multiproc - multithread

These are two very different things, it's important to know the difference in order to attribute the error to something.
Also, AFAIK docker only supports one process per container (but this might have changed since my last interaction).

> Managed to reproduce in docker only.

I'm going to go out on a limb here and say this issue is most likely linked to the use of docker.
I'll close it for now, and you can re-open when it's reproducible in a common scenario.

**Closed as completed** 2020-08-21 19:59 UTC
